### ISSUE TITLE
npm install node-sass does not work inside php-fpm due to missing python dep

### ISSUE THREAD

**Issue by mokanfar** [swiftotter/den#157]
My build relies on gulp sass -> css compilation, `snowdog/frontools` to be exact. I get an error when trying to run `gulp styles` in php-fpm container:
`It seems there is no binary available for your platform/architecture` 
Is there a workaround for getting it to work on this project? I can not run it on my host machine as the pub/static folder is not synced. Thank you for your help.

**Comment by navarr** [comment]
I see that you used the right template, but deleted all the headings which walked you through the useful information I'll need to handle this bug.

While this likely applies to all images, I'm not familiar with those tools and so having a minimal reproducible project to recreate them against would work wonders here for helping me fix this issue.

Could you please provide sort of the minimum information I need to reproduce this bug? - essentially a gulp project that will exhibit the error

**Comment by mokanfar** [comment]
Hi @navarr sorry when making new issue I did not see the template, trying again I do see it flash fast before clearing. Im guessing it is a bug with github: https://imgur.com/a/vXi5Wah

**Version of Den**
1.0.0-beta.11

**Image**
ghcr.io/swiftotter/den-php-fpm-magento2:7.4-node14

**Describe the bug**
can not install node-sass, due to missing python dep 

**To Reproduce**
Steps to reproduce the behavior:
```
den shell
npm install node-sass
```

**Expected behavior**
npm installs necessary node-sass. 

**Actual result**
npm fails installing with error:
````
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs

> node-sass@8.0.0 install /var/www/html/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/www-data/.npm/node-sass/8.0.0/linux-arm64-83_binding.node

> node-sass@8.0.0 postinstall /var/www/html/node_modules/node-sass
> node scripts/build.js

Binary found at /var/www/html/node_modules/node-sass/vendor/linux-arm64-83/binding.node
Testing binary
Binary has a problem: Error: Error loading shared library /var/www/html/node_modules/node-sass/vendor/linux-arm64-83/binding.node: Exec format error
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at module.exports (/var/www/html/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/var/www/html/node_modules/node-sass/lib/index.js:13:35)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_DLOPEN_FAILED'
}
Building the binary locally
Building: /usr/local/bin/node /var/www/html/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/bin/node',
gyp verb cli   '/var/www/html/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@8.4.1
gyp info using node@14.21.1 | linux | arm64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - "python3" is not in PATH or produced an error
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - "python" is not in PATH or produced an error
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/var/www/html/node_modules/node-sass/node_modules/node-gyp/lib/find-python.js:330:47)
gyp ERR! stack     at PythonFinder.runChecks (/var/www/html/node_modules/node-sass/node_modules/node-gyp/lib/find-python.js:159:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/var/www/html/node_modules/node-sass/node_modules/node-gyp/lib/find-python.js:202:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/var/www/html/node_modules/node-sass/node_modules/node-gyp/lib/find-python.js:294:16)
gyp ERR! stack     at exithandler (child_process.js:390:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:402:5)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:472:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
gyp ERR! System Linux 5.15.49-linuxkit
gyp ERR! command "/usr/local/bin/node" "/var/www/html/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/www/html/node_modules/node-sass
gyp ERR! node -v v14.21.1
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok
Build failed with error code: 1
npm WARN enoent ENOENT: no such file or directory, open '/var/www/html/package.json'
npm WARN html No description
npm WARN html No repository field.
npm WARN html No README data
npm WARN html No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@8.0.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@8.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/www-data/.npm/_logs/2022-11-10T05_57_18_118Z-debug.log
```
seems problem is actually with node-sass, and part of the suite of tools needed to compile sass->css. Edited title to reflect accuracy.

**Comment by mokanfar** [comment]
Thank you so much that worked! ❤️
